config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'
  get 'detail' => 'entries#detail'
  get 'contact' => 'entries#contact'
  resources :entries
  devise_for :users

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :amount, presence: true, length: { maximum: 20 }
  validates	:category,     presence: true
  validates	:entry_date,   presence: true
  validates	:balance_type, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!, only: [ :detail, :show, :new, :create, :edit, :update, :destroy ]

  def index
    date_string      = (params[:sort_month] && params[:sort_month]!="")?(params[:sort_month]):(Date.current.strftime('%Y-%m'))
    @entries         = Entry.where("cast(entry_date as text) LIKE '#{date_string}%'").paginate(page: params[:page], :per_page => 20).order('entry_date DESC')

    if Rails.env.development?
      @entries_select  = Entry.select('strftime(\'%Y-%m\', entry_date) AS date_prefix').group('strftime(\'%Y-%m\', entry_date)').order('entry_date DESC')
    elsif Rails.env.production?
      @entries_select  = Entry.select("to_char(entry_date, 'YYYY-MM') AS date_prefix").group("to_char(entry_date, 'YYYY-MM')").order("to_char(entry_date, 'YYYY-MM') DESC")
    end

    @entries_data    = Entry.where("cast(entry_date as text) LIKE '#{date_string}%' AND balance_type = 'Expense'").group(:category).sum(:amount)
    @title           = (params[:sort_month] && params[:sort_month]!="")? "#{params[:sort_month].split("-")[0]}年 #{params[:sort_month].split("-")[1]}月 紀錄" : "#{Date.current.strftime('%Y')}年 #{Date.current.strftime('%m')}月 紀錄"
    @entries_balance = Entry.where("cast(entry_date as text) LIKE '#{date_string}%'").group(:balance_type).sum(:amount)

    @entries_balance["Income"] = 0 if @entries_balance["Income"].nil?
    @entries_balance["Expense"] = 0 if @entries_balance["Expense"].nil?
  end

  def detail
  end

  def show
    @entry = Entry.find(params[:id])
    render 'detail'
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:info] = "Successfully Created 新增成功"
      redirect_to @entry
    else
      render 'new'
    end
  end

  def edit
    @entry = Entry.find(params[:id])
    render 'detail'
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update(entry_params)
      flash[:info] = "Successfully Modified 修改成功"
      redirect_to @entry
    else
      render 'detail'
    end
  end

  def destroy
    @entry = Entry.find(params[:id]).destroy
    flash[:info] = "Successfully Deleted 刪除成功"
    redirect_to entries_url
  end

  def contact

  end

  def after_sign_in_path_for(resource)
    redirect_to :index
  end

  private

  def entry_params
    params.require(:entry).permit(:amount, :category, :balance_type, :description, :entry_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = "")
    base_title = "Plutus"

    if title.empty?
      base_title
    else
      "#{title} | #{base_title}"
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/common/_error_messages.html.erb
<% if @entry.errors.any? %>
  <div id="" class="panel panel-danger">
    <div class="panel-heading">
      You have <%= pluralize(@entry.errors.count, "error") %> while entering.
	</div>
    <div class="panel-body">
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/entries/_full_form_fields.html.erb
<%= render 'common/error_messages' %>
<%= f.label :balance_type, "收支類型" %>
<%= f.select(:balance_type, options_for_select([['請選擇', ''], ['支出', 'Expense'], ['收入', 'Income']], @entry.balance_type), {}, class: 'select-tag') %>
<%= f.label :category, "項目類別" %>
<%= f.text_field :category %>
<%= f.label :amount, "金額" %>
<%= f.text_field :amount %>
<%= f.label :entry_date, "日期" %>
<div>
  <%= f.date_select( :entry_date, 
		               {
		               	 start_year: 2015, 
		                 selected: Date.today, 
		               }, 
	                   class: "select-tag col-md-4 col-sm-4 col-xs-12" 
                   ) %>
</div>
<%= f.label :description, "備註" %>
<%= f.text_area :description %>

app/views/entries/contact.html.erb
<h1>Contact me</h1>
<div class="well">
  <p>Email: onyxlw@yahoo.com.tw</p>
  <p>Just contact me if you'd like to talk to me.</p>
</div>

app/views/entries/detail.html.erb
<% provide(:title, "Detail") %>
<h1>"<%= @entry.category %>"的細節</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <%= form_for(@entry) do |f| %>
      <%= render 'full_form_fields', f: f %>
      <%= f.submit "Modify This Record確認修改", class: "btn btn-primary" %>
      <%= link_to "Cancel", root_path %>
    <% end %>
  </div>
</div>

app/views/entries/index.html.erb
<h1><%= @title %></h1>
<aside class="col-md-4 col-sm-6 col-xs-12">
  <form action="/entries" method="GET" id="search">
    <div class="form-group">
      <%= select_tag "sort_month", options_from_collection_for_select(@entries_select, 'date_prefix', 'date_prefix', params[:sort_month] ), include_blank: "Choose Month 選擇顯示月份", class: "form-control" %>
    </div>
  </form>
  <div id="container" style="min-width: 220px; min-height: 400px;"></div>
  <div id="container2" style="min-width: 220px; min-height: 300px; margin: 5px auto"></div>
</aside>
<div class="col-md-8 col-sm-6 col-xs-12">
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr class="info">
          <th>Date 日期</th>
          <th>Type 支出/消費</th>
          <th>category 消費項目</th>
          <th>Amount 消費金額</th>
          <th>Operation 操作</th>
        </tr>
      </thead>
      <tbody>
        <% @entries.each do |entry| %>
          <tr class="">
            <td><%= entry.entry_date %></td>
            <td><%= (entry.balance_type == "Expense") ? "Expense支出" : "Income收入" %></td>
            <td><%= entry.category %></td>
            <td><%= entry.amount %></td>
            <% if user_signed_in? %>
              <td>
                <%= link_to "Edit修改", edit_entry_path(entry), class: 'btn btn-primary btn-xs' %>
                <%= link_to "Delete刪除", entry_path(entry), method: :delete, data:{ confirm: "確定刪除嗎?" }, class: 'btn btn-danger btn-xs' %>
              </td>
            <% else %>
              <td>
                <%= link_to "Login請登入", new_user_session_path, :class => 'btn btn-success btn-xs'  %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
  </div>
</div>
<div class="clearfix"></div>
<script type="text/javascript">
  $("#sort_month").on("change", function() {
    $("#search").submit();
  });
  $(function () {
  /**
   * Dark theme for Highcharts JS
   * @author Torstein Honsi
   */
  // Load the fonts
  Highcharts.createElement('link', {
    href: '//fonts.googleapis.com/css?family=Unica+One',
    rel: 'stylesheet',
    type: 'text/css'
  }, null, document.getElementsByTagName('head')[0]);
  
  Highcharts.theme = {
    colors: ["#2b908f", "#90ee7e", "#f45b5b", "#7798BF", "#aaeeee", "#ff0066", "#eeaaee",
    "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
    chart: {
      backgroundColor: {
        linearGradient: { x1: 0, y1: 0, x2: 1, y2: 1 },
        stops: [
        [0, '#2a2a2b'],
        [1, '#3e3e40']
        ]
      },
      style: {
        fontFamily: "'Unica One', sans-serif"
      },
      plotBorderColor: '#606063'
    },
    title: {
      style: {
        color: '#E0E0E3',
        textTransform: 'uppercase',
        fontSize: '20px'
      }
    },
    subtitle: {
      style: {
        color: '#E0E0E3',
        textTransform: 'uppercase'
      }
    },
    xAxis: {
      gridLineColor: '#707073',
      labels: {
        style: {
          color: '#E0E0E3'
        }
      },
      lineColor: '#707073',
      minorGridLineColor: '#505053',
      tickColor: '#707073',
      title: {
        style: {
          color: '#A0A0A3'
  
        }
      }
    },
    yAxis: {
      gridLineColor: '#707073',
      labels: {
        style: {
          color: '#E0E0E3'
        }
      },
      lineColor: '#707073',
      minorGridLineColor: '#505053',
      tickColor: '#707073',
      tickWidth: 1,
      title: {
        style: {
          color: '#A0A0A3'
        }
      }
    },
    tooltip: {
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      style: {
        color: '#F0F0F0'
      }
    },
    plotOptions: {
      series: {
        dataLabels: {
          color: '#B0B0B3'
        },
        marker: {
          lineColor: '#333'
        }
      },
      boxplot: {
        fillColor: '#505053'
      },
      candlestick: {
        lineColor: 'white'
      },
      errorbar: {
        color: 'white'
      }
    },
    legend: {
      itemStyle: {
        color: '#E0E0E3'
      },
      itemHoverStyle: {
        color: '#FFF'
      },
      itemHiddenStyle: {
        color: '#606063'
      }
    },
    credits: {
      style: {
        color: '#666'
      }
    },
    labels: {
      style: {
        color: '#707073'
      }
    },
  
    drilldown: {
      activeAxisLabelStyle: {
        color: '#F0F0F3'
      },
      activeDataLabelStyle: {
        color: '#F0F0F3'
      }
    },
  
    navigation: {
      buttonOptions: {
        symbolStroke: '#DDDDDD',
        theme: {
          fill: '#505053'
        }
      }
    },
  
   // scroll charts
   rangeSelector: {
    buttonTheme: {
      fill: '#505053',
      stroke: '#000000',
      style: {
        color: '#CCC'
      },
      states: {
        hover: {
          fill: '#707073',
          stroke: '#000000',
          style: {
            color: 'white'
          }
        },
        select: {
          fill: '#000003',
          stroke: '#000000',
          style: {
            color: 'white'
          }
        }
      }
    },
    inputBoxBorderColor: '#505053',
    inputStyle: {
      backgroundColor: '#333',
      color: 'silver'
    },
    labelStyle: {
      color: 'silver'
    }
   },
  
   navigator: {
    handles: {
      backgroundColor: '#666',
      borderColor: '#AAA'
    },
    outlineColor: '#CCC',
    maskFill: 'rgba(255,255,255,0.1)',
    series: {
      color: '#7798BF',
      lineColor: '#A6C7ED'
    },
    xAxis: {
      gridLineColor: '#505053'
    }
   },
  
   scrollbar: {
    barBackgroundColor: '#808083',
    barBorderColor: '#808083',
    buttonArrowColor: '#CCC',
    buttonBackgroundColor: '#606063',
    buttonBorderColor: '#606063',
    rifleColor: '#FFF',
    trackBackgroundColor: '#404043',
    trackBorderColor: '#404043'
   },
  
   // special colors for some of the
   legendBackgroundColor: 'rgba(0, 0, 0, 0.5)',
   background2: '#505053',
   dataLabelsColor: '#B0B0B3',
   textColor: '#C0C0C0',
   contrastTextColor: '#F0F0F3',
   maskColor: 'rgba(255,255,255,0.3)'
  };
  
  // Apply the theme
  Highcharts.setOptions(Highcharts.theme);
  
    var option = {
        chart: {
          renderTo: 'container',
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Expense Analysis 消費分析'
        },
        tooltip: {
            pointFormat: '<b>{series.name}: $ {point.y:.0f}</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    connectorWidth: 0,
                    distance: 10,
                    format: '<b> {point.percentage:.1f} %</b>',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black',
                        fontSize: "11px",
                        fontWeight: "bold"
                    }
                },
                showInLegend: true
            }
        },
        series: [{
            type: 'pie',
            name: 'Expense',
            data: [
            <% if @entries_data.any? %>
                <% @entries_data.each do |key, value| %>
                ['<%= key %>', <%= value %>],
                <% end %>
            <% else %>
                ['None', 1],
            <% end %>
            ]
        }]
    }
    var chart1 = new Highcharts.Chart(option);
  
  $(function () {
    <% if @entries_balance.any? %>
    Highcharts.setOptions({
        colors: ['<%= (@entries_balance["Income"] > @entries_balance["Expense"])? "#7cb5ec" : "#FF0000" %>', '#434348', '#90ed7d' ]
    });
    <% end %>
    $('#container2').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Finance Balance 收支平衡'
        },
        // subtitle: {
        //     text: 'Source: Wikipedia.org'
        // },
        xAxis: {
            // categories: ['Expense', 'Income', 'Balance'],
            categories: ['Balance'],
            title: {
                text: null
            }
        },
        yAxis: {
            title: {
                text: 'Dollars',
                align: 'high'
            },
            labels: {
                overflow: 'justify'
            }
        },
        tooltip: {
            valueSuffix: ''
        },
        plotOptions: {
            bar: {
                dataLabels: {
                    enabled: true
                }
            }
        },
        legend: {
          enabled: true,
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'top',
            x: -5,
            y: 25,
            floating: true,
            borderWidth: 1,
            backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
            shadow: true
        },
        credits: {
            enabled: false
        },
        series: [{
            name: 'Balance',
            data: [<%= (@entries_balance.any?)?(@entries_balance["Income"]-@entries_balance["Expense"]):0 %>],
        }, {
            name: 'Income',
            data: [<%= (@entries_balance.any?)?(@entries_balance["Income"]):0 %>]
        }, {
            name: 'Expense',
            data: [<%= (@entries_balance.any?)?(@entries_balance["Expense"]):0 %>],
        }]
    });
  });
  
  });
</script>

app/views/entries/new.html.erb
<% provide(:title, 'Enter') %>
<h1>Add An Entry</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <%= form_for(@entry) do |f| %>
      <%= render 'full_form_fields', f: f %>
      <%= f.submit "Send This Record送出", class: "btn btn-primary" %>
      <%= link_to "Cancel", root_path %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://github.com/HydnWang/plutus">Personal Financial Management App</a>
    by <a href="https://github.com/HydnWang">Hayden Wang</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><a href="https://github.com/HydnWang/plutus">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_form.html.erb
<!-- <form class="form-horizontal">
  <fieldset>
    <legend>Legend</legend>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-10">
        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Password</label>
      <div class="col-lg-10">
        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
        <div class="checkbox">
          <label>
            <input type="checkbox"> Checkbox
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="textArea" class="col-lg-2 control-label">Textarea</label>
      <div class="col-lg-10">
        <textarea class="form-control" rows="3" id="textArea"></textarea>
        <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-2 control-label">Radios</label>
      <div class="col-lg-10">
        <div class="radio">
          <label>
            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
            Option one is this
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
            Option two can be something else
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="select" class="col-lg-2 control-label">Selects</label>
      <div class="col-lg-10">
        <select class="form-control" id="select">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
        <br>
        <select multiple="" class="form-control">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="reset" class="btn btn-default">Cancel</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form> -->

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <!-- <span class="sr-only">Toggle navigation</span> -->
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "PLUTUS", root_path, id: "logo" %>
    </div>
    <nav class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Add a record", new_entry_path %></li>
          <li><%= link_to "#{current_user.email}'s profile", edit_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, , maximum-scale=1.0, user-scalable=no">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid" style="margin-top: 20px;">
      <% if !notice && !alert %>
        <% flash.each do |type, msg| %>
          <div class="alert alert-<%= type %>"><%= msg %></div>
        <% end %>
      <% end %>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>